apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # API Extensions (listed individually so new clusters get what they want not everyhitng)
  - ../../base/apiextensions.k8s.io/customresourcedefinitions/applications.argoproj.io
  - ../../base/apiextensions.k8s.io/customresourcedefinitions/applicationsets.argoproj.io
  - ../../base/apiextensions.k8s.io/customresourcedefinitions/appprojects.argoproj.io
  - ../../base/apiextensions.k8s.io/customresourcedefinitions/cronworkflows.argoproj.io
  - ../../base/apiextensions.k8s.io/customresourcedefinitions/extensions.dashboard.tekton.dev
  - ../../base/apiextensions.k8s.io/customresourcedefinitions/prowjobs.prow.k8s.io
  - ../../base/apiextensions.k8s.io/customresourcedefinitions/sealedsecrets.bitnami.com
  - ../../base/apiextensions.k8s.io/customresourcedefinitions/workflow.argoproj.io
  - ../../base/apiextensions.k8s.io/customresourcedefinitions/workflowtemplate.argoproj.io
  # Namespaces
  - ../../base/core/namespaces/apex
  - ../../base/core/namespaces/apex-monitoring
  - ../../base/core/namespaces/apex-qa
  - ../../base/core/namespaces/copilot-ops
  - ../../base/core/namespaces/dex
  - ../../base/core/namespaces/ipfs
#  - ../../base/core/namespaces/janus-idp
#  - ../../base/core/namespaces/robozome
#  - ../../base/core/namespaces/sigstore-aas
#  - ../../base/core/namespaces/tekton-pipelines
#  - ../../base/core/namespaces/thoth-amun-api-prod
#  - ../../base/core/namespaces/thoth-amun-inspection-prod
#  - ../../base/core/namespaces/thoth-backend-prod
#  - ../../base/core/namespaces/thoth-bots-prod
#  - ../../base/core/namespaces/thoth-cre-integration
#  - ../../base/core/namespaces/thoth-deployment-examples
#  - ../../base/core/namespaces/thoth-frontend-prod
#  - ../../base/core/namespaces/thoth-graph-prod
#  - ../../base/core/namespaces/thoth-infra-prod
#  - ../../base/core/namespaces/thoth-middletier-prod
  # Operatorgroups and subscriptions
  - ../../base/operators.coreos.com/operatorgroups/apex
  - ../../base/operators.coreos.com/subscriptions/crunchy-postgres
  # Premade bundles (some may include CRDs)
  - ../../bundles/acme-operator
  - ../../bundles/cert-manager
  - ../../bundles/jaeger-operator
  - ../../bundles/opentelemetry-collector-operator
  - ../../bundles/tekton-chains
  # Cluster Specific Cluster-scoped resources
  - apiserver/api_server_cert.yaml
  - clusterversion.yaml
  - ingresscontrollers/default.yaml
