---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acme-operator
spec:
  destination:
    name: in-cluster
    namespace: acme-operator
  project: rosa
  source:
    path: acme-operator/overlays/rosa
    repoURL: https://github.com/gregory-pereira/rosa-apps.git
    targetRevision: migrate-op1st-argocd-to-rosa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
  ignoreDifferences:
    - group: ""
      jsonPointers:
        - /data/cert-issuer.types.acme.openshift.io
      kind: ConfigMap
      name: letsencrypt-live
      namespace: acme-operator
