---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-tekton-chains
spec:
  project: rosa
  source:
    repoURL: https://github.com/operate-first/continuous-delivery.git
    path: tekton-chains/overlays/moc
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: tekton-chains
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - Validate=false
