apiVersion: kustomize.config.k8s.io/v1beta1
components:
    - ../../../../components/project-admin-rolebindings/rosa
    - ../../../../components/limitranges/default
    - ../../../../components/resourcequotas/small
kind: Kustomization
namespace: dex
resources:
    - namespace.yaml
