apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/sealed-secrets
  - ../../base/rbac.authorization.k8s.io/clusterroles/sealed-secrets
