---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acme-operator
resources:
- namespace.yaml
components:
- ../../../../components/project-admin-rolebindings/rosa
- ../../../../components/resourcequotas/x-small
- ../../../../components/limitranges/default
