apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-route53-credentials
  namespace: openshift-ingress
spec:
  encryptedData:
    aws_secret_access_key: AgBACs+us9IuH6weowF8sMWcAfbqJ9BbEii8O/vpOc8YAOQvGwde196Uhh3BuqcMAahzS3CLjuQbJrm2w7RJvrdM1j7AN69we57AuKcl+v07c98+Ip13ox02lvGeCF62YBJjv8e4oQedy0NRREPmZWiQ4z65C38lRBxUQ8VTi1atoQdzlQyhOF3KFBBbcyU3h8fcPGhz1yIaz4CUdn4IYuW6LrvdjwBCF6Y8ABrk1rh//T+Pv5+wue+PUuyi4u4TRrKKQOSd+KnxljLaUOhOlVOYaASrB8HH1ZplzAaMlHe97RKg1lYEBl7IN19ubItGFvy0MywwUCKAbVCUS0S25vvVLy3rHHkBpml0C+jM3ORtS2FSMZ2sTuMzeTiitvEliKRpxRbSee6dcCWfyN3BpD3Nv2NsJEn0lE8Zyv7yUsmaifIeO4vHPsn1auz90B9cYQl+UNBS9U2mRS+OXIAC4kt+r7Udpos77DXSklAInwwow6RlUNX9Yl4/I+xuPo1iHfj14bje2YEE1jZrwzW+nAfUyXFMjsuiDZs/H8/Pk8y2DTgqYzDPcF/rHZuv9AhkP4uuSDbF/MOLwx/SwQAMUtZG0QwGHFHtSHg24WAd0SFRkWfyu+g3Pthy+8xuUz4GXFT7+4Ul3n0MMb7GArdoA+TRF/LXYPYIEI19EzV5KGKr+8R/C7w+zreLA/ryddZg2/Sv0Udnlpi6MU9rflfzbeSVxzhDvoaNyB5DOTkggX/ws0+chO+bIIeQ
  template:
    metadata:
      creationTimestamp: null
      name: aws-route53-credentials
      namespace: openshift-ingress
    type: Opaque
