apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
namespace: keycloak-system
components:
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/large
