apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate
  namespace: openshift-ingress
spec:
  dnsNames:
  - '*.apps.open-svc-sts.k1wl.p1.openshiftapps.com'
  duration: 2160h0m0s
  issuerRef:
    name: ingress-letsencrypt
  renewBefore: 360h0m0s
  secretName: ingress-certificate
