apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: openshift-gitops
    name: in-cluster
  project: rosa
  source:
    path: argocd/overlays/rosa
    repoURL: https://github.com/gregory-pereira/rosa-apps.git
    targetRevision: migrate-op1st-argocd-to-rosa
  syncPolicy:
    syncOptions:
      - Validate=false
