apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  project: rosa
  source:
    path: argocd/overlays/rosa/projects
    repoURL: https://github.com/gregory-pereira/rosa-apps.git
    targetRevision: migrate-op1st-argocd-to-rosa
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - Validate=false
