apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  project: cluster-management
  source:
    path: argocd/overlays/rosa/projects
    repoURL: https://github.com/redhat-et/rosa-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - Validate=false
