apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    name: moc-infra
    namespace: argocd
  project: default
  source:
    path: argocd/overlays/rosa
    repoURL: https://github.com/redhat-et/rosa-apps.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Validate=false
