apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    name: in-cluster
    namespace: openshift-ingress
  project: cluster-management
  source:
    repoURL: https://github.com/redhat-et/rosa-apps.git
    path: cert-manager/overlays/rosa
    targetRevision: main
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - Validate=false
