apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-resources
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  project: cluster-management
  source:
    path: cluster-scope/overlays/rosa
    repoURL: https://github.com/gregory-pereira/rosa-apps.git
    targetRevision: migrate-op1st-argocd-to-rosa
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - Validate=false
#     - ApplyOutOfSyncOnly=true
