---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
spec:
  destination:
    name: in-cluster
    namespace: dex
  project: cluster-management
  source:
    path: dex/overlays/rosa
    repoURL: https://github.com/redhat-et/rosa-apps.git
    targetRevision: main
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - Validate=false
