apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apex
spec:
  destination:
    name: in-cluster
    namespace: apex
  source:
    path: deploy/apex/overlays/prod
    repoURL: 'https://github.com/gregory-pereira/apex'
    targetRevision: update-apex-auth-cert-certificate
  project: apex
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
