apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apex-qa
spec:
  destination:
    name: in-cluster
    namespace: apex-qa
  source:
    path: deploy/apex/overlays/qa
    repoURL: "https://github.com/gregory-pereira/apex"
    targetRevision: update-apex-auth-cert-certificate
  project: apex
  # syncPolicy:
  #   syncOptions:
  #     - Replace=true
  #   automated:
  #     prune: true
