apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/project-admin-rolebindings/rosa
- ../../../../components/monitoring-rbac
- ../../../../components/limitranges/default
kind: Kustomization
namespace: rosa-monitoring
resources:
- namespace.yaml
- resourcequota.yaml
