kind: Route
apiVersion: route.openshift.io/v1
metadata:
    name: argocd-google
    annotations:
        kubernetes.io/tls-acme: "true"
spec:
    host: argocd.rosa.cloud
    to:
        kind: Service
        name: openshift-gitops-server
        weight: 100
