apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: rosa-vault-snapshots
spec:
  bucketName: rosa-vault-snapshots
  objectBucketName: obc-vault-rosa-vault-snapshots
  storageClassName: openshift-storage.noobaa.io
