kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: rosa-vault-ui
  namespace: vault
spec:
  to:
    kind: Service
    name: rosa-vault
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: http
