apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/core/namespaces/openshift-serverless
  - ../../base/operators.coreos.com/operatorgroups/openshift-serverless
  - ../../base/operators.coreos.com/subscriptions/openshift-serverless
