apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/core/namespaces/rosa-monitoring
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/rosa-monitoring-grafana-cluster-view
  - grafana-serviceaccount.yaml
