apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-rosa
spec:
  destination:
    namespace: openshift-gitops
    name: in-cluster
  project: rosa
  source:
    path: argocd/overlays/rosa/applications/envs/rosa
    repoURL: https://github.com/gregory-pereira/rosa-apps.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - Validate=false
    - ApplyOutOfSyncOnly=true
