apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service-account.yaml
  - ../../cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/sealed-secrets
  - ../../cluster-scope/base/rbac.authorization.k8s.io/clusterroles/sealed-secrets
  - ../../cluster-scope/base/rbac.authorization.k8s.io/rolebindings/sealed-secrets
  - ../../cluster-scope/base/rbac.authorization.k8s.io/roles/sealed-secrets
  - service.yaml
