apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
  name: openshift-gitops-argocd-dex-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-argocd-dex-server
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-server
  namespace: openshift-gitops
