kind: Secret
apiVersion: v1
metadata:
  name: cluster-spec-moc-infra
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: argocd-infra
    argocd.argoproj.io/secret-type: cluster
data:
  config: >-
    eyJiZWFyZXJUb2tlbiI6ICJleUpoYkdjaU9pSlNVekkxTmlJc0ltdHBaQ0k2SWxkeE4zWXRUMEZmTkhwaFVsWk1Vek15U1ZkemFFOXlYM1JMVFRaUVNHTmZXbTlHT0Zjd05rZHlVRTBpZlEuZXlKcGMzTWlPaUpyZFdKbGNtNWxkR1Z6TDNObGNuWnBZMlZoWTJOdmRXNTBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5dVlXMWxjM0JoWTJVaU9pSmhjbWR2WTJRaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sWTNKbGRDNXVZVzFsSWpvaVlYSm5iMk5rTFcxaGJtRm5aWEl0ZEc5clpXNHRibkp4Y1hNaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNXVZVzFsSWpvaVlYSm5iMk5rTFcxaGJtRm5aWElpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1MWFXUWlPaUl4WWpRME9HVmpNaTFtWmpZd0xUUmlNR0l0WVdJMVpTMDRZbVZpWTJNMlptUTNNbUVpTENKemRXSWlPaUp6ZVhOMFpXMDZjMlZ5ZG1salpXRmpZMjkxYm5RNllYSm5iMk5rT21GeVoyOWpaQzF0WVc1aFoyVnlJbjAubWFEaFYyYmU5UUlCeFhuN0hoTHpJUVFXWTdYeFo5cC1RWnJMMVRqOFBodzY4U0FaUTRRRzVsLWJwb2k4aW1xa29DQ2VrYTFvUEhOTUFKVkpramdjekNzTkdYbFhlTDJzc2hva0xrc1V4Um4zVkhDUGJibWtwemFJLU1yazU1X3czSDEydG1WTnMzS1VoRTF4aDhGU3BUbW9FRzRCaHkxWXF2MnZpVnhHV3hvbkRpZE4yN1ZWUF91cTNuWGlWV3ltVU1DUGNwUWp0ZmkyNld4Z0ZZZFhkcnpaSHBpTnI3Z2pMOUZvOWtNU0tmWG1nUzVIWmt6dC00WnZaU29qQ24zakNwZEtEWkZVZXBNRUJwaHZyVEM0T1cxelFhZjZDYWVZOVZPdzg2VVJLSUlnTFI4Q0M0cHMtZ1pkUFJtakNvWlFkazR1U0xaaGZvcDRMWl9FOGJMY1JnIiwgInRsc0NsaWVudENvbmZpZyI6IHsiaW5zZWN1cmUiOiB0cnVlfX0K
  name: bW9jLWluZnJh
  server: aHR0cHM6Ly9hcGkubW9jLWluZnJhLm1hc3NvcGVuLmNsb3VkOjY0NDM=
type: Opaque
