apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-certificate-letsencrypt
spec:
  dnsNames:
  - octo-emerging.redhataicoe.com
  duration: 2160h0m0s
  issuerRef:
    name: ingress-letsencrypt
  renewBefore: 360h0m0s
  secretName: api-certificate
