---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: grafana
spec:
  deployment:
    labels:
      app.kubernetes.io/name: grafana-oauth
    envFrom:
      # - secretRef:
      #     name: oauth-client-secret
      # - secretRef:
      #     name: grafana-secret-config
      - configMapRef:
          name: grafana-config-overrides
  configMaps:
    - grafana-landing-page
  serviceAccount:
    labels:
      app.kubernetes.io/instance: cluster-resources
  config:
    server:
      root_url: https://grafana.open-svc-sts.k1wl.p1.openshiftapps.com
    dashboards:
      default_home_dashboard_path: "/etc/grafana-configmaps/grafana-landing-page/landingpage.json"
    auth.generic_oauth:
      enabled: true
      scopes: openid email groups profile
      email_attribute_path: name
      client_id: grafana
      client_secret: "${GRAFANA_CLIENT_SECRET}"
      api_url: https://dex-dex.apps.open-svc-sts.k1wl.p1.openshiftapps.com/userinfo
      auth_url: https://dex-dex.apps.open-svc-sts.k1wl.p1.openshiftapps.com/auth
      token_url: https://dex-dex.apps.open-svc-sts.k1wl.p1.openshiftapps.com/token
      role_attribute_path: >-
        contains(groups[*], 'cluster-admins') && 'Admin' ||
        'Deny'
      role_attribute_strict: true
