---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: trusted-artifact-signer
  releaseName: trusted-artifact-signer
  valuesFile: values.yaml
  repo: https://repo-securesign-helm.apps.open-svc-sts.k1wl.p1.openshiftapps.com/helm-charts
  version: 0.1.12
resources:
- ../../cluster-scope/base/core/namespaces/fulcio-system
- ../../cluster-scope/base/core/namespaces/rekor-system