issuer: https://dex-dex.apps.open-svc-sts.k1wl.p1.openshiftapps.com

storage:
  type: memory

web:
  http: "0.0.0.0:5556"

grpc:
  addr: "0.0.0.0:5557"

telemetry:
  http: "0.0.0.0:5558"

oauth2:
  skipApprovalScreen: true

# staticClients:
#   - id: grafana
#     name: Grafana
#     redirectURIs:
#       - https://grafana.open-svc-sts.k1wl.p1.openshiftapps.com/login/generic_oauth
#       - http://grafana.open-svc-sts.k1wl.p1.openshiftapps.com/login/generic_oauth
#     secretEnv: GRAFANA_SECRET

connectors:
  - type: openshift
    id: openshift
    name: OpenShift
    config:
      issuer: https://kubernetes.default.svc
      clientID: system:serviceaccount:dex:dex
      clientSecret: $OPENSHIFT_CLIENT_SECRET
      redirectURI: https://dex-dex.apps.open-svc-sts.k1wl.p1.openshiftapps.com/callback
      groups:
        - system:authenticated
